# Data Wrangling HW

>Brynn O'Toole

## Quiz Questions

### Question 1

In [1]:
import pandas as pd

### Question 2

In [8]:
df = pd.read_csv("sales.csv")

### Question 3

In [9]:
df.head(5)

,order_id,order_date,product_id,store_id,customer_id,quantity,unit_price,discount,revenue,cost,profit
0,0RD00000001,2023-01-07,P0080,S093,C040749,5,14.43,0.15,61.33,42.77,18.56
1,0RD00000002,2023-10-22,P0173,S065,C020161,3,12.01,0.00,36.03,19.06,16.97
2,0RD00000003,2023-05-07,P0115,S078,C048069,2,10.02,0.00,20.04,10.29,9.75
3,0RD00000004,2024-06-23,P0186,S088,C047901,2,14.66,0.10,26.39,16.35,10.04
4,0RD00000005,2024-09-24,P0197,S054,C033950,1,12.34,0.00,12.34,7.94,4.40

### Question 4

In [10]:
df.shape

(1000000, 11)

### Question 5

In [11]:
df.columns

Index(['order_id', 'order_date', 'product_id', 'store_id', 'customer_id',
       'quantity', 'unit_price', 'discount', 'revenue', 'cost', 'profit'],
      dtype='object')

### Question 6

In [14]:
 df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 11 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   order_id     1000000 non-null  object
 1   order_date   1000000 non-null  object
 2   product_id   1000000 non-null  object
 3   store_id     1000000 non-null  object
 4   customer_id  1000000 non-null  object
 5   quantity     1000000 non-null  int64
 6   unit_price   1000000 non-null  float64
 7   discount     1000000 non-null  float64
 8   revenue      1000000 non-null  float64
 9   cost         1000000 non-null  float64
 10  profit       1000000 non-null  float64
dtypes: float64(5), int64(1), object(5)
memory usage: 83.9+ MB

### Question 7

In [19]:
df[df['unit_price'] > 5]

,order_id,order_date,product_id,store_id,customer_id,quantity,unit_price,discount,revenue,cost,profit
0,0RD00000001,2023-01-07,P0080,S093,C040749,5,14.43,0.15,61.33,42.77,18.56
1,0RD00000002,2023-10-22,P0173,S065,C020161,3,12.01,0.00,36.03,19.06,16.97
2,0RD00000003,2023-05-07,P0115,S078,C048069,2,10.02,0.00,20.04,10.29,9.75
3,0RD00000004,2024-06-23,P0186,S088,C047901,2,14.66,0.10,26.39,16.35,10.04
4,0RD00000005,2024-09-24,P0197,S054,C033950,1,12.34,0.00,12.34,7.94,4.40
...,...,...,...,...,...,...,...,...,...,...,...
999994,0RD00999995,2024-07-28,P0127,S055,C007369,1,8.96,0.20,7.17,4.73,2.44
999995,0RD00999996,2023-04-15,P0103,S053,C044763,4,7.45,0.00,29.80,17.27,12.53
999996,0RD00999997,2023-05-26,P0094,S058,C004441,2,6.09,0.00,12.18,7.81,4.37
999997,0RD00999998,2023-07-05,P0097,S041,C044879,3,6.09,0.00,18.27,10.11,8.16
999999,0RD01000000,2024-04-10,P0175,S090,C025078,1,7.35,0.10,6.62,3.33,3.28

### Question 8

In [21]:
df[["unit_price", "quantity"]]

        unit_price  quantity
0            14.43         5
1            12.01         3
2            10.02         2
3            14.66         2
4            12.34         1
...            ...       ...
999995        7.45         4
999996        6.09         2
999997        6.09         3
999998        4.90         1
999999        7.35         1

[1000000 rows x 2 columns]

### Question 9

In [22]:
df.rename(columns={'unit_price':'Alpha'}, inplace=True)
df.columns

Index(['order_id', 'order_date', 'product_id', 'store_id', 'customer_id',
       'quantity', 'Alpha', 'discount', 'revenue', 'cost', 'profit'],
      dtype='object')

### Question 10

In [25]:
df.replace(999, pd.NA, inplace=True)

### Question 11

In [26]:
df.dropna()

,order_id,order_date,product_id,store_id,customer_id,quantity,Alpha,discount,revenue,cost,profit
0,0RD00000001,2023-01-07,P0080,S093,C040749,5,14.43,0.15,61.33,42.77,18.56
1,0RD00000002,2023-10-22,P0173,S065,C020161,3,12.01,0.00,36.03,19.06,16.97
2,0RD00000003,2023-05-07,P0115,S078,C048069,2,10.02,0.00,20.04,10.29,9.75
3,0RD00000004,2024-06-23,P0186,S088,C047901,2,14.66,0.10,26.39,16.35,10.04
4,0RD00000005,2024-09-24,P0197,S054,C033950,1,12.34,0.00,12.34,7.94,4.40
...,...,...,...,...,...,...,...,...,...,...,...
999995,0RD00999996,2023-04-15,P0103,S053,C044763,4,7.45,0.00,29.80,17.27,12.53
999996,0RD00999997,2023-05-26,P0094,S058,C004441,2,6.09,0.00,12.18,7.81,4.37
999997,0RD00999998,2023-07-05,P0097,S041,C044879,3,6.09,0.00,18.27,10.11,8.16
999998,0RD00999999,2024-01-03,P0090,S083,C042525,1,4.90,0.00,4.90,2.56,2.34
999999,0RD01000000,2024-04-10,P0175,S090,C025078,1,7.35,0.10,6.62,3.33,3.28

### Question 12

In [29]:
df.fillna(0)

,order_id,order_date,product_id,store_id,customer_id,quantity,Alpha,discount,revenue,cost,profit
0,0RD00000001,2023-01-07,P0080,S093,C040749,5,14.43,0.15,61.33,42.77,18.56
1,0RD00000002,2023-10-22,P0173,S065,C020161,3,12.01,0.00,36.03,19.06,16.97
2,0RD00000003,2023-05-07,P0115,S078,C048069,2,10.02,0.00,20.04,10.29,9.75
3,0RD00000004,2024-06-23,P0186,S088,C047901,2,14.66,0.10,26.39,16.35,10.04
4,0RD00000005,2024-09-24,P0197,S054,C033950,1,12.34,0.00,12.34,7.94,4.40
...,...,...,...,...,...,...,...,...,...,...,...
999995,0RD00999996,2023-04-15,P0103,S053,C044763,4,7.45,0.00,29.80,17.27,12.53
999996,0RD00999997,2023-05-26,P0094,S058,C004441,2,6.09,0.00,12.18,7.81,4.37
999997,0RD00999998,2023-07-05,P0097,S041,C044879,3,6.09,0.00,18.27,10.11,8.16
999998,0RD00999999,2024-01-03,P0090,S083,C042525,1,4.90,0.00,4.90,2.56,2.34
999999,0RD01000000,2024-04-10,P0175,S090,C025078,1,7.35,0.10,6.62,3.33,3.28

### Question 13

In [30]:
df['Alpha'].mean()

np.float64(9.002449039999998)

### Question 14

In [31]:
df['C'] = df['Alpha'] + df['quantity']

### Question 15

In [32]:
df.to_csv('output.csv', index=False)