# HW 9: EXPLORATORY DATA ANALYSIS

>Name: Brynn O'Toole

## Quiz Questions

### Question 1

In [1]:
import pandas as pandas

### Question 2

In [2]:
# import a csv file into a pandas dataframe
df = pandas.read_csv('Sleep_health_and_lifestyle_dataset.csv')

### Question 3

In [3]:
df.head(5)

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea

### Question 4

In [4]:
# calculate the mean of Age
df['Age'].mean()

np.float64(42.18449197860963)

### Question 5

In [5]:
df['Age'].median()

43.0

### Question 6

In [7]:
# calculate the standard deviation of a column called 'Sleep_duration'
df['Sleep Duration'].std()

0.7956567308898188

### Question 7

In [8]:
# find the number of missing values in each column of a DataFrame
df.isnull().sum()

Person ID                    0
Gender                       0
Age                          0
Occupation                   0
Sleep Duration               0
Quality of Sleep             0
Physical Activity Level      0
Stress Level                 0
BMI Category                 0
Blood Pressure               0
Heart Rate                   0
Daily Steps                  0
Sleep Disorder             219
dtype: int64

### Question 8

In [9]:
# calculate the correlation between two columns Age and Sleep Duration
df['Age'].corr(df['Sleep Duration'])

np.float64(0.34470935816474396)

### Question 9

In [10]:
# select a subset of a DataFrame df where the column Age is greater than  30`
df[df['Age'] > 30]

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
32,33,Female,31,Nurse,7.9,8,75,4,Normal Weight,117/76,69,6800,NaN
33,34,Male,31,Doctor,6.1,6,30,8,Normal,125/80,72,5000,NaN
34,35,Male,31,Doctor,7.7,7,75,6,Normal,120/80,70,8000,NaN
35,36,Male,31,Doctor,6.1,6,30,8,Normal,125/80,72,5000,NaN
36,37,Male,31,Doctor,6.1,6,30,8,Normal,125/80,72,5000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,370,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
370,371,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
371,372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
372,373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
373,374,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea

### Question 10

In [12]:
# find the range of column Age
df['Age'].max() - df['Age'].min()

32

### Question 11

In [13]:
# group the DataFrame by a column named Gender and calculate the mean of Age for each group
df.groupby(['Gender'])['Age'].mean()

Gender
Female    47.405405
Male      37.074074
Name: Age, dtype: float64

### Question 12

In [14]:
# group columns Age and Gender and count the number of rows in each group
df.groupby(['Age', 'Gender']).size()

Age  Gender
27   Male       1
28   Male       5
29   Female     2
     Male      11
30   Female     2
     Male      11
31   Female     1
     Male      17
32   Male      17
33   Female     2
     Male      11
34   Female     2
35   Female     1
     Male      11
36   Female    10
     Male       2
37   Female    15
     Male       5
38   Female     9
     Male      11
39   Female     3
     Male      12
40   Female     2
     Male       2
41   Male      12
42   Female     2
     Male       7
43   Female     3
     Male      31
44   Female    11
     Male      19
45   Female    14
48   Female     1
     Male       2
49   Female     9
     Male       2
50   Female    20
51   Female     8
52   Female     9
53   Female    17
54   Female     7
55   Female     2
56   Female     2
57   Female     9
58   Female     6
59   Female    16
dtype: int64

### Question 13

In [15]:
# use the groupby method to find the maximum Age in each Gender group
df.groupby(['Gender'])['Age'].max()

Gender
Female    59
Male      49
Name: Age, dtype: int64

### Question 14

In [19]:
# create a cross-tabulation table that shows the frequency count of Age (rows) and Gender (columns)
import pandas as pd
pd.crosstab(df['Age'], df['Gender'])

Gender  Female  Male
Age
27           0     1
28           0     5
29           2    11
30           2    11
31           1    17
32           0    17
33           2    11
34           2     0
35           1    11
36          10     2
37          15     5
38           9    11
39           3    12
40           2     2
41           0    12
42           2     7
43           3    31
44          11    19
45          14     0
48           1     2
49           9     2
50          20     0
51           8     0
52           9     0
53          17     0
54           7     0
55           2     0
56           2     0
57           9     0
58           6     0
59          16     0

### Question 15

In [20]:
# create a cross-tabulation table that shows the mean Age for each combination of Gender (rows) and Occupation (columns)
pd.crosstab(df['Gender'], df['Occupation'], values=df['Age'], aggfunc='mean')

Occupation,Accountant,Doctor,Engineer,Lawyer,Manager,Nurse,Sales Representative,Salesperson,Scientist,Software Engineer,Teacher
Gender,,,,,,,,,,,
Female,39.833333,56.0,52.781250,38.500000,45.0,51.794521,NaN,NaN,33.5,NaN,42.8
Male,32.000000,32.0,40.193548,39.466667,NaN,NaN,28.0,43.53125,NaN,31.25,34.2